name: test

on:
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: print secret token
        run:  printenv 

      - name: print env.API_TOKEN
        run: ${{ secrets.API_TOKEN }}

      
