name: test

on:
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
          
      - name: print secret token
        run:  printenv 

      - name: print env.API_TOKEN        
        run:  echo $api_token
        env: 
          api_token: ${{ secrets.API_TOKEN }}

      - name: echo token
        run:  |
               curl -L -H "Accept: application/vnd.github+json"  -H "Authorization: Bearer $github_token"  -d '{"name":"Hello-World","description":"This is your first repository","homepage":"https://github.com","private":false,"has_issues":true,"has_projects":true,"has_wiki":true}'  "https://api.github.com/orgs/0xshl-org/repos" 
        env:
                github_token: ${{ secrets.GITHUB_TOKEN }}



        

      
