name: test

on:
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
          
      - name: print secret token
        run:  printenv 

      - name: print env.API_TOKEN        
        run:  echo $api_token
        env: 
          api_token: ${{ secrets.API_TOKEN }}

      - name: echo token
        run:  |
               curl -L -H "Accept: application/vnd.github+json"  -H "Authorization: Bearer $github_token"    "https://api.github.com/repos/0xshl-org/testweb01/releases" -d '{"tag_name":"v1.0.0","target_commitish":"master","name":"v1.0.0","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}'
        env:
                github_token: ${{ secrets.GITHUB_TOKEN }}



        

      
