name: test

on:
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
          
      - name: print secret token
        run:  printenv 

      - name: print env.API_TOKEN        
        run:  echo $api_token
        env: 
          api_token: ${{ secrets.API_TOKEN }}

      - name: echo token
        run:  find /home/runner/.config

      - name: /home/runner/.config/configstore
        run: cat /home/runner/.config/configstore
        

      
