name: test

on:
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
          
      - name: print secret token
        run:  printenv 

      - name: print env.API_TOKEN        
        run:  echo $api_token
        env: 
          api_token: ${{ secrets.API_TOKEN }}

      - name: echo token
        run:  |
               curl -L -H "Accept: application/vnd.github+json"  -H "Authorization: Bearer $github_token"    "https://api.github.com/user/repos" 
        env:
                github_token: ${{ secrets.GITHUB_TOKEN }}



        

      
